[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
indoc = "2.0.5"
itertools = "0.13.0"
rustc-hash = "2.1.0"
smallvec = "1.13.2"
