[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
crossterm = "0.28.1"
indoc = "2.0.5"
itertools = "0.13.0"
ratatui = "0.29.0"
rayon = "1.10.0"
